# Generated by Django 2.2 on 2019-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
