# Generated by Django 2.2 on 2019-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no',
            field=models.IntegerField(),
        ),
    ]
