# Generated by Django 2.2 on 2019-04-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190401_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no',
        ),
    ]
